---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test
  namespace: mc
spec:
  releaseName: test
  chart:
    git: git@github.com:HRZNStudio/playhrzn-k8s
    ref: master
    path: charts/minecraft
  values:
    domain: playhrzn.com
    minecraftServer:
      image: itzg/minecraft-server:latest@sha256:f9d1ba5c5adaac0c9aabed234a4b74463d0ebc09e47e6c71b5a623435cee0138
      eula: "TRUE"
      version: "1.14.4"
      type: "PAPER"
