---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: metricbeat
  namespace: elastic-stack
spec:
  releaseName: metricbeat
  chart:
    repository: https://helm.elastic.co
    name: metricbeat
    version: 7.6.2
  values:
    daemonset:
      metricbeatConfig:
        metricbeat.yml: |
          metricbeat.modules:
            - module: prometheus
              period: 10s
              hosts: ["prometheus-operator-prometheus.monitoring:9090"]
              metrics_path: /metrics
            - module: kubernetes
              metricsets:
                - container
                - node
                - pod
                - system
                - volume
              period: 10s
              host: "${NODE_NAME}"
              hosts: ["https://${NODE_NAME}:10250"]
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              ssl.verification_mode: "none"
              processors:
                - add_kubernetes_metadata: ~
            - module: kubernetes
              enabled: true
              metricsets:
                - event
            - module: system
              period: 10s
              metricsets:
                - cpu
                - load
                - memory
                - network
                - process
                - process_summary
              processes: ['.*']
              process.include_top_n:
                by_cpu: 5
                by_memory: 5
            - module: system
              period: 1m
              metricsets:
                - filesystem
                - fsstat
              processors:
              - drop_event.when.regexp:
                  system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
          output.elasticsearch:
            hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
